### PR TITLE
OS-JR Reflection Implementation + Dev Patches 12/9/17

### PR DESCRIPTION
**Pull request by zeruth**
https://github.com/zeruth/OSJR

I've been working on my Reflection interface OS-JR for quite some time. I've made tremendous progress internally but visually my client was plain jane. I stumbled upon this client and decided to try and throw my client in.

**# I personally use Eclipse, so if this gets merged, you will have to add the 3 new libs in /resources**

I have added the following though, which is worth checking out:

-Auto gamepack updater, no more "osrs is loading". This only has to run when a revision change occurs.
downloading gamepack
This cuts loading times down to a fraction of a second. plus who doesn't love a progress bar?

-Full reflection Interface: LOTS of hooks already implemented
hooks
Hooks easily called anywhere via Hooks.selector. example:

int healthBarMax = Hooks.selector.client.getLocalPlayer.asActor.getHealthBarMax();
Local players can be called, player xps, etc the list goes on.

I update the hooks weekly usually shortly after patch day. There is a built in fallback mode. Hooks get disasbled until they can be updated automagically.

Overall was just messing around, but I feel like it turned out pretty nice so thought I'd share.

UPDATE:
Bringup of Dev patches

Renamed the packages to conform to your package structure.

Set the gamepack and game settings directory to USER/Luna
-settings only holds live gamepack filesize (and now notes), and the key is to cache gamepacks based on filesize for ultra fast startup times.

Added a save button for Notes, as well as an auto loader at bootup
Fixed client not being able to snap to sides of desktop in later windows versions.
Added OSB style username in gameFrame title.

UPDATE 🍰 
Added sidebar skill focus:
logged in player levels will be shown by default on login.
Whatever skill you last gained xp in will be focused in the sidebar until xp is gained in another skill or another skill is highlighted.
These are populated via reflection, and are always updated.
skill focus

UPDATE 🐄 
Updates to UTCClock and skillInfo panel
updated paint

IMO this merger adds a ton of features to the client by way of reflection, and paves the way for a OSBuddy / Konduit Open Source alternative.

### CODE REVIEW

**Comment by Talon876** [comment]
This looks awesome @zeruth. Out of curiosity do your hooks support fetching the player's current location?

**Comment by SomeoneWithAnInternetConnection** [comment]
I'm not super familiar with NetBeans or Ant, but this PR doesn't seem to have have the classpath configured correctly for the ant build stuff: none of the new jars are present. I was able to fix it by manually adding references for the new jars in `nbproject/project.properties` (see the `files.reference.foo` section that starts on line 32, and the companion `javac.classpath` at line 50), but I suspect netbeans has some more convenient UI for doing that.

Unfortunately I still still couldn't build it:
```
-do-compile:
    [mkdir] Created dir: /tmp/osrsclient/build/empty
    [mkdir] Created dir: /tmp/osrsclient/build/generated-sources/ap-source-output
    [javac] Compiling 96 source files to /tmp/osrsclient/build/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] /tmp/osrsclient/src/rsclient/coregui/RSClient.java:93: error: local variable mainpanel is accessed from within inner class; needs to be declared final
    [javac] 				fullscreen(full, mainpanel, sidepanel, bottompanel, gamepanel);
    [javac] 				                 ^
    [javac] /tmp/osrsclient/src/rsclient/coregui/RSClient.java:93: error: local variable sidepanel is accessed from within inner class; needs to be declared final
    [javac] 				fullscreen(full, mainpanel, sidepanel, bottompanel, gamepanel);
    [javac] 				                            ^
    [javac] /tmp/osrsclient/src/rsclient/coregui/RSClient.java:93: error: local variable bottompanel is accessed from within inner class; needs to be declared final
    [javac] 				fullscreen(full, mainpanel, sidepanel, bottompanel, gamepanel);
    [javac] 				                                       ^
    [javac] Note: /tmp/osrsclient/src/rsclient/market/ItemResultPanel.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 3 errors
    [javac] 1 warning
```
It looks like Java 8 can figure out when things are effectively final, but Java 7 (which the project is configured to build for) needs an explicit definition.
Marking `mainpanel`, `sidepanel` and `bottompanel` as `final` seems to have fixed the build issues though.

Here's the diff of the changes I had to make to get it to build:
```diff
diff --git a/nbproject/project.properties b/nbproject/project.properties
index 4c66582..a519264 100755
--- a/nbproject/project.properties
+++ b/nbproject/project.properties
@@ -29,8 +29,10 @@ dist.jar=${dist.dir}/RSClient.jar
 dist.javadoc.dir=${dist.dir}/javadoc
 endorsed.classpath=
 excludes=
+file.reference.asm-5.1.0.jar=src/resources/asm-5.1.0.jar
 file.reference.commons-io-2.4.jar=src/resources/commons-io-2.4.jar
 file.reference.commons-lang3-3.3.2.jar=src/resources/commons-lang3-3.3.2.jar
+file.reference.gson-2.2.4.jar=src/resources/gson-2.2.4.jar
 file.reference.guava-16.0.1.jar=src/resources/guava-16.0.1.jar
 file.reference.guava-18.0.jar=src/resources/guava-18.0.jar
 file.reference.jerklib.jar=src/resources/jerklib.jar
@@ -40,15 +42,18 @@ file.reference.pircbot.jar=src/resources/pircbot.jar
 file.reference.pircbotx-2.0.1.jar=src/resources/pircbotx-2.0.1.jar
 file.reference.slf4j-api-1.7.7.jar=src/resources/slf4j-api-1.7.7.jar
 file.reference.slf4j-simple-1.7.7.jar=src/resources/slf4j-simple-1.7.7.jar
+file.reference.swf.jar=src/resources/swt.jar
 file.reference.tinylaf.jar=src/resources/tinylaf.jar
 file.reference.trident.jar=src/resources/trident.jar
 includes=**
 jar.compress=true
 javac.classpath=\
+    ${file.reference.asm-5.1.0.jar}:\
     ${file.reference.commons-io-2.4.jar}:\
     ${file.reference.commons-lang3-3.3.2.jar}:\
     ${file.reference.guava-16.0.1.jar}:\
     ${file.reference.guava-18.0.jar}:\
+    ${file.reference.gson-2.2.4.jar}:\
     ${file.reference.jerklib.jar}:\
     ${file.reference.json_simple-1.0.2.jar}:\
     ${file.reference.miglayout-4.0.jar}:\
@@ -56,6 +61,7 @@ javac.classpath=\
     ${file.reference.pircbotx-2.0.1.jar}:\
     ${file.reference.slf4j-api-1.7.7.jar}:\
     ${file.reference.slf4j-simple-1.7.7.jar}:\
+    ${file.reference.swf.jar}:\
     ${file.reference.tinylaf.jar}:\
     ${file.reference.trident.jar}
 # Space-separated list of extra javac options
diff --git a/src/rsclient/coregui/RSClient.java b/src/rsclient/coregui/RSClient.java
index 7b76929..5a0ea0f 100755
--- a/src/rsclient/coregui/RSClient.java
+++ b/src/rsclient/coregui/RSClient.java
@@ -59,7 +59,7 @@ public class RSClient {
 
 		lunaFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
 
-		JPanel mainpanel = new JPanel(new MigLayout("fill, insets 5"));
+		final JPanel mainpanel = new JPanel(new MigLayout("fill, insets 5"));
 		mainpanel.setBackground(Color.black);
 		rsclient.game.RSGame rsgame = new rsclient.game.RSGame();
 		rsgame.run();
@@ -74,8 +74,8 @@ public class RSClient {
 																							// 765:765:765,
 		gamepanel.setVisible(true);
 
-		JPanel sidepanel = new JPanel(new MigLayout("ins 0"));
-		JPanel bottompanel = new JPanel(new MigLayout("ins 0"));
+		final JPanel sidepanel = new JPanel(new MigLayout("ins 0"));
+		final JPanel bottompanel = new JPanel(new MigLayout("ins 0"));
 		sidepanel.setBackground(Color.black);
 		bottompanel.setBackground(Color.black);
 
```

**Comment by bmoyer** [comment]
Just from a quick read of your description, I am really pleased with this. It's awesome that you were able to finally get something going in the way of reflection, I think that could be really big for this client.

Give me some time to read and try the code and I'll give further feedback. Loving the looks of this, nice work.

**Comment by zeruth** [comment]
@Talon876 Absolutely. I'm always updating the hooks as well.

@SomeoneWithAnInternetConnection Yeah I use Eclipse, its been home to me for a long time lol. I knew you would have to manually add those libs. I'm sorry for the hassle.
And my bad on the J8 issue, I had to create a new project to get it into eclipse, so it never knew anything about the old project. and J8 is my default target.

@bmoyer yeah it's a lot to look at I know. the bread and butter is all in Hooks and HookUpdater.

You can call any hook via Hooks.selector from ANY class.
I try to cache common data under HookUpdater as well as other repeated client tasks.

It's a lot to take in, it's 1000's of lines lol. But I designed it to be easy. Easy to use, Easy to modify.
Play around with it, and you'll love it.

**Comment by zeruth** [comment]
Closing for new and improved Pull Request.

**Pull request closed without merging**
